name: Trips

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./apis/trips
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...
      working-directory: ${{env.working-directory}}

    - name: Test
      run: go test -v ./tests
      working-directory: ${{env.working-directory}}
